### ISSUE TITLE
トップページ、銭湯ぐらしとは？のテキストを改行なしにして欲しい。

### ISSUE THREAD

**Issue by yu-sukey** [sentogurashi/template#49]
高円寺の銭湯「小杉湯」のとなりに、2018年2月に解体が決まった、風呂なしアパートがあります。解体までの期間、このアパートに多彩な仲間たちが暮らしはじめました。それぞれの個性と得意分野を活かした彼らの“銭湯ぐらし”は、銭湯と人の新しい物語をつむぎ出していくことになりそうです。

**Comment by tarezou** [comment]
反映しました。
